import { useState } from 'react';
import { ArrowRight, CheckCircle2, ClipboardList, Globe2, LockKeyhole, Package, Search, Truck, Users } from 'lucide-react';
type View='home'|'book'|'track'|'login';
const features=[
 ['Live shipment tracking','Track milestones without exposing private customer data.',Globe2],
 ['Fast cargo booking','Create a shipment request and receive a unique booking reference.',ClipboardList],
 ['Fleet operations','Manage vehicles, drivers, routes and active trips from one workplace.',Truck],
 ['Role-based security','Separate customer, driver, staff and administrator permissions.',LockKeyhole],
] as const;

export default function App(){
 const [view,setView]=useState<View>('home');
 const navigate=(next:View)=>{setView(next);window.scrollTo({top:0,behavior:'auto'});};
 if(view==='login')return <Login onBack={()=>navigate('home')}/>;
 return <div className="app">
  <header className="nav"><button className="brand" onClick={()=>navigate('home')}><span className="brand-mark">K</span><span><strong>KERENGA</strong><small>CARGO COURIERS</small></span></button>
  <nav><button onClick={()=>navigate('home')}>Home</button><button onClick={()=>navigate('book')}>Book Cargo</button><button onClick={()=>navigate('track')}>Track</button><button className="nav-login" onClick={()=>navigate('login')}>Workplace Login</button></nav></header>
  {view==='home'&&<Home onNavigate={navigate}/>} {view==='book'&&<Booking onBack={()=>navigate('home')}/>} {view==='track'&&<Tracking onBack={()=>navigate('home')}/>}
  <footer><div><strong>KERENGA CARGO COURIERS</strong><p>Reliable movement. Clear visibility. Secure operations.</p></div><span>© {new Date().getFullYear()} Kerenga Cargo Couriers</span></footer>
 </div>;
}
function Home({onNavigate}:{onNavigate:(v:View)=>void}){return <main>
 <section className="hero"><div className="eyebrow">LOGISTICS • CARGO • DELIVERY</div><h1>Move cargo with <em>confidence.</em></h1><p>A modern logistics platform for booking consignments, monitoring shipments and running your transport operation from one secure system.</p><div className="actions"><button className="primary" onClick={()=>onNavigate('book')}>Book a Shipment <ArrowRight size={18}/></button><button className="secondary" onClick={()=>onNavigate('track')}>Track Cargo <Search size={18}/></button></div><div className="hero-stats"><span><b>24/7</b> shipment visibility</span><span><b>4</b> secure workspaces</span><span><b>1</b> operations platform</span></div></section>
 <section className="section"><div className="section-head"><div className="eyebrow">BUILT FROM YOUR EXISTING PLATFORM</div><h2>The useful parts, rebuilt cleanly.</h2></div><div className="feature-grid">{features.map(([title,body,Icon])=><article className="card" key={title}><Icon size={22}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="split section"><div><div className="eyebrow">FOR CUSTOMERS</div><h2>Book, receive a reference, then track.</h2><p>The public side stays simple. Customers do not need access to internal operational records just to see shipment status.</p><button className="primary" onClick={()=>onNavigate('book')}>Start a Booking <ArrowRight size={18}/></button></div><div className="visual-card"><Package size={44}/><div><b>KCC-2026-0001</b><span>IN TRANSIT</span></div><div className="progress"><i/><i/><i/><i/></div><small>Nairobi → Kampala → Kigali</small></div></section>
 </main>}
function Booking({onBack}:{onBack:()=>void}){
 const [result,setResult]=useState<string|null>(null);
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setResult(null);const data=Object.fromEntries(new FormData(e.currentTarget));const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await response.json();setResult(response.ok?'Booking created: '+body.reference:(body.error||'Booking failed.'));};
 return <main className="form-page"><button className="back" onClick={onBack}>← Back</button><div className="form-shell"><div><div className="eyebrow">NEW CONSIGNMENT</div><h1>Book your cargo</h1><p>Submit the shipment details. The backend validates the request and stores the booking in Firestore.</p>{result&&<div className="notice"><CheckCircle2 size={20}/><span>{result}</span></div>}</div><form onSubmit={submit}><label>Sender name<input name="senderName" required placeholder="Full name or company"/></label><label>Phone<input name="phone" required placeholder="+254 ..."/></label><label>Email<input name="email" type="email" placeholder="you@example.com"/></label><div className="two"><label>Origin<input name="origin" required placeholder="Nairobi, Kenya"/></label><label>Destination<input name="destination" required placeholder="Kampala, Uganda"/></label></div><label>Cargo description<textarea name="cargoDescription" required placeholder="What are you sending?"/></label><div className="two"><label>Weight (kg)<input name="weightKg" required type="number" min="0"/></label><label>Packages<input name="packages" required type="number" min="1"/></label></div><button className="primary">Create Booking <ArrowRight size={18}/></button></form></div></main>}
function Tracking({onBack}:{onBack:()=>void}){
 const [result,setResult]=useState<any>(null); const [error,setError]=useState('');
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setResult(null);const data=Object.fromEntries(new FormData(e.currentTarget));const response=await fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await response.json();if(!response.ok){setError(body.error||'Unable to verify shipment.');return;}setResult(body);};
 return <main className="form-page"><button className="back" onClick={onBack}>← Back</button><div className="tracking-shell"><div className="eyebrow">PUBLIC TRACKING</div><h1>Track a consignment</h1><p>Enter the shipment reference and the same phone number used when the booking was created.</p><form className="track-input" onSubmit={submit}><input name="trackingNumber" required placeholder="e.g. KCC-2026-0001"/><input name="phone" required placeholder="+254 ..."/><button className="primary">Track <Search size={18}/></button></form>{error&&<div className="notice">{error}</div>}{result&&<div className="notice"><CheckCircle2 size={20}/><span><b>{result.trackingNumber}</b> — {result.status} — {result.origin} → {result.destination}</span></div>}<div className="notice"><CheckCircle2 size={20}/><span>Privacy-first tracking: public results show shipment milestones, not private customer, driver or document data.</span></div></div></main>}
function Login({onBack}:{onBack:()=>void}){return <main className="form-page"><button className="back" onClick={onBack}>← Back</button><div className="login-shell"><div className="brand-mark large">K</div><div className="eyebrow">SECURE WORKPLACE</div><h1>Sign in</h1><p>One authentication layer, with permissions determining the workplace you can access.</p><form onSubmit={e=>{e.preventDefault();alert('Sample login screen. Firebase Authentication will be connected here.')}}><label>Email<input type="email" required placeholder="you@company.com"/></label><label>Password<input type="password" required placeholder="••••••••"/></label><button className="primary">Sign in <ArrowRight size={18}/></button></form><div className="role-row"><span><Users size={16}/> Customer</span><span><Truck size={16}/> Driver</span><span><LockKeyhole size={16}/> Staff/Admin</span></div></div></main>}
